# Generated by Django 3.0.2 on 2020-02-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wallet',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.TextField(default='#'),
        ),
    ]
