# Generated by Django 3.0.2 on 2020-02-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200201_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.TimeField(auto_created=True, auto_now=True),
        ),
    ]
